### ISSUE TITLE
FMessageBox crashes with strings length longer than terminal window.

### ISSUE THREAD

**Issue by WarShoe** [gansm/finalcut#6] opened 2017-02-23 10:41 UTC
Consider the following code. It works fine with short (less than terminal window width) strings, and crashes with long.

```
#include "final.h"

int main (int argc, char* argv[])
{
    if( argc!=2 )
        return 1;
    FApplication app(argc,argv);
    FMessageBox info ( "Greeting",argv[1], FMessageBox::Ok, 0, 0, &app );
    info.show();
    return 0;
}

```

**Comment by gansm** [comment] 2017-02-25 14:30
I found the cause of the crash. The two variables offset_left and offset_top was swapped in the class FVTerm. This is now fixed.

**Closed** 2017-04-26 17:18 UTC
Labels: bug
