### ISSUE TITLE
Bus error in "windows" example.

### ISSUE THREAD

**Issue by WarShoe** [gansm/finalcut#8] opened 2017-11-03 08:47 UTC
Here are my actions:
- git clone
- compile code (make)
- go to 'examples' directory
- run ./windows (or .libs/windows)
- in the 'windows' application I click "Create", "Quit", "Yes" (to confirm the quit)

On the program exit I receive "Bus error".

finalcut version: from the repository, last commit 64a8041bcfe1fbcacb2c4f6c238906561feaf09e, Fri Nov 3 05:04:27

**Comment by gansm** [comment] 2017-11-03 22:08
I could not reproduce the bus error on my PC. But I found out that closing the main window (class Window) deletes all own sub-window data (`win_data`) via the destructor. But the individual sub-windows are still there. They will be terminated later by the destructor of `FObject`. Therefore, every sub-window sends a "destroy" signal. The signal calls the callback-method `Window::cb_destroyWindow`, which wants to use the deleted sub-window data.

I fixed this bug with the last commit.

----
If the bus error is still occurring, check if you still have an old version of the library installed. 

What is the output of
```bash
cd examples/.libs
ldd windows | grep libfinal.so.0
```

Are the checksums the same?
```bash
md5sum $(ldd windows | grep libfinal.so.0 | awk '{print $3}')
md5sum ../../src/.libs/libfinal.so.0.3.0
```

Which operating system (on which architecture) do you use?
Which kernel (version) do you use?

You could also run the following command and send me the output of "valgrind.txt".
```bash
LD_LIBRARY_PATH=../../src/.libs/ valgrind --tool=memcheck --suppressions=../../doc/ncurses.supp --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes --track-origins=yes --log-file=./valgrind.txt windows
```

**Comment by WarShoe** [comment] 2017-11-09 17:28
My bad, indeed it was picking up an old library version.

**Closed** 2017-11-09 19:04 UTC
